project:
  template:
    dir: "templates/melon"
    output: "../../Java/weimob-inf"
  includes: []
  data:
    project_name: "weimob-inf"
    tables:
      - {
          prefix: "e_third_",
          name: "weimob_customer_create",
          columns:
            [
              {
                name: "id",
                type: "Long",
                dbType: "NUMBER(15)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "eid",
                type: "String",
                dbType: "VARCHAR2(120)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "topic",
                type: "String",
                dbType: "VARCHAR2(120)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "event",
                type: "String",
                dbType: "VARCHAR2(120)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "wid",
                type: "String",
                dbType: "VARCHAR2(120)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "bos_id",
                type: "Long",
                dbType: "NUMBER(32)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "sign",
                type: "String",
                dbType: "VARCHAR2(120)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "scene_type",
                type: "Long",
                dbType: "NUMBER(2)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "plan_id",
                type: "Long",
                dbType: "NUMBER(32)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "type",
                type: "Long",
                dbType: "NUMBER(2)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "wid_list",
                type: "String",
                dbType: "VARCHAR2(3000)",
                skip: [1, 1, 1, 1],
              },
            ],
          ddls: [],
        }
    ddls: [""]
