project:
  template:
    dir: "templates/guava"
    output: "../guava-erp"
  data:
    project_name: "guava-erp"
    tables:
      - {
          name: "category",
          ddls: ["create table category(id int8, name text, pid int8);"],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1] },
              { name: "pid", type: "i64", skip: [1, 1, 1, 1] },
            ],
        }
      - {
          name: "attribute",
          ddls: ["create table attribute(id int8, name text);"],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1] },
            ],
        }
      - {
          name: "attribute_value",
          ddls:
            [
              "create table attribute_value(id int8, name text, attribute_id int8);",
            ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1] },
              { name: "attribute_id", type: "i64", skip: [1, 1, 1, 1] },
            ],
        }
      - {
          name: "unit",
          ddls:
            [
              "create table unit(id int8, code text, name text, description text);",
            ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "code", type: "String", skip: [1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1] },
              { name: "description", type: "String", skip: [1, 1, 1, 1] },
            ],
        }
      - {
          name: "brand",
          ddls:
            [
              "create table brand(id int8, code text, name text, description text);",
            ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "code", type: "String", skip: [1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1] },
              { name: "description", type: "String", skip: [1, 1, 1, 1] },
            ],
        }
      # 仓库
      - {
          name: "warehouse",
          ddls:
            [
              "create table warehouse(id int8, code text, name text, contacts text, phone text, address text, description text);",
            ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "code", type: "String", skip: [1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1] },
              { name: "contacts", type: "String", skip: [1, 1, 1, 1] },
              { name: "phone", type: "String", skip: [1, 1, 1, 1] },
              { name: "address", type: "String", skip: [1, 1, 1, 1] },
              { name: "description", type: "String", skip: [1, 1, 1, 1] },
            ],
        }
      # 门店
      - {
          name: "merchant",
          ddls:
            [
              "create table merchant(id int8, code text, name text, contacts text, phone text, address text, tax text, bank text, account text, description text);",
            ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "code", type: "String", skip: [1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1] },
              { name: "contacts", type: "String", skip: [1, 1, 1, 1] },
              { name: "phone", type: "String", skip: [1, 1, 1, 1] },
              { name: "address", type: "String", skip: [1, 1, 1, 1] },
              { name: "tax", type: "String", skip: [1, 1, 1, 1] },
              { name: "bank", type: "String", skip: [1, 1, 1, 1] },
              { name: "account", type: "String", skip: [1, 1, 1, 1] },
              { name: "description", type: "String", skip: [1, 1, 1, 1] },
            ],
        }
      # 结算账户
      - {
          name: "account",
          ddls:
            [
              "create table account(id int8, code text, name text, create_date date, initial decimal(14,4), balance decimal(14,4), description text);",
            ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "code", type: "String", skip: [1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1] },
              {
                name: "create_date",
                type: "Date",
                default: "Date(fastdate::DateTime::now().into())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "initial",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "balance",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 0, 1, 1, 1],
              },
              { name: "description", type: "String", skip: [1, 1, 1, 1, 1] },
            ],
        }
      # 供应商
      - {
          name: "supplier",
          ddls:
            [
              "create table supplier(id int8, code text, name text, contacts text, phone text, email text, address text, tax text, bank text, account text, arrears decimal(14,4), begin_arrears decimal(14,4), description text);",
            ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "code", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "contacts", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "phone", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "email", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "address", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "tax", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "bank", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "account", type: "String", skip: [1, 1, 1, 1, 1] },
              {
                name: "arrears",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "begin_arrears",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              { name: "description", type: "String", skip: [1, 1, 1, 1, 1] },
            ],
        }
      # 客户
      - {
          name: "customer",
          ddls:
            [
              "create table customer(id int8, code text, name text, contacts text, phone text, email text, address text, tax text, bank text, account text, integral decimal(14,4), discount decimal(14,4), arrears decimal(14,4), begin_arrears decimal(14,4), description text);",
            ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "code", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "contacts", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "phone", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "email", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "address", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "tax", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "bank", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "account", type: "String", skip: [1, 1, 1, 1, 1] },
              {
                name: "discount",
                type: "Decimal",
                default: "Decimal(1.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "integral",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "arrears",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "begin_arrears",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              { name: "description", type: "String", skip: [1, 1, 1, 1, 1] },
            ],
        }
      # 商品
      - {
          name: "product",
          ddls:
            [
              "create table product( id int8, code text, name text, serialno text, spec text, category_id int8, brand_id int8, unit_id int8, is_multi_unit bool, multi_unit_list text, description text, warehouse_id int8, location text, stocktip int8, retail_name text, details text, is_multi_price bool, buy decimal(14,4), sell decimal(14,4), retail decimal(14,4), integral decimal(14,4));",
            ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "code", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "serialno", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "spec", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "category_id", type: "i64", skip: [1, 1, 1, 1, 1] },
              { name: "brand_id", type: "i64", skip: [1, 1, 1, 1, 1] },
              { name: "unit_id", type: "i64", skip: [1, 1, 1, 1, 1] },
              { name: "is_multi_unit", type: "i8", skip: [1, 1, 1, 1, 1] },
              {
                name: "multi_unit_list",
                type: "String",
                skip: [1, 1, 1, 1, 1],
              },
              { name: "description", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "warehouse_id", type: "i64", skip: [1, 1, 1, 1, 1] },
              { name: "location", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "stocktip", type: "i64", skip: [1, 1, 1, 1, 1] },
              { name: "retail_name", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "is_multi_price", type: "i8", skip: [1, 1, 1, 1, 1] },
              {
                name: "buy",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "sell",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "retail",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "integral",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              { name: "is_active", type: "i8", skip: [1, 1, 1, 1, 1] },
            ],
        }
      # asi
      - {
          name: "asi",
          ddls:
            [
              "create table asi( id int8, code text, name text, nod text, product_id int8 );",
            ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "code", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "nod", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "product_id", type: "i64", skip: [1, 1, 1, 1] },
              {
                name: "is_active",
                type: "i8",
                default: "1",
                skip: [1, 1, 1, 1, 1],
              },
            ],
        }
        # sku
      - {
          name: "sku",
          ddls:
            [
              "create table sku( id int8, code text, name text, product_id int8, asi_id int8, buy decimal(14,4), sell decimal(14,4), retail decimal(14,4));",
            ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "code", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "product_id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "asi_id", type: "i64", skip: [1, 1, 1, 1] },
              {
                name: "buy",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "sell",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "retail",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "is_active",
                type: "i8",
                default: "1",
                skip: [1, 1, 1, 1, 1],
              },
            ],
        }
      # 多单位
      - {
          name: "multi_unit",
          ddls:
            [
              "create table multi_unit( id int8, code text, name text, product_id int8, unit_id int8, qty decimal(14,4));",
            ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "code", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "product_id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "unit_id", type: "i64", skip: [1, 1, 1, 1] },
              {
                name: "qty",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "is_active",
                type: "i8",
                default: "1",
                skip: [1, 1, 1, 1, 1],
              },
            ],
        }
      # 多单位价格
      - {
          name: "sku_unit_price",
          ddls:
            [
              "create table sku_unit_price( id int8, code text, name text, product_id int8, asi_id int8, sku_id int8, unit_id int8, buy decimal(14,4), sell decimal(14,4), retail decimal(14,4));",
            ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "code", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1, 1] },
              { name: "product_id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "asi_id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "sku_id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "unit_id", type: "i64", skip: [1, 1, 1, 1] },
              {
                name: "buy",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "sell",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "retail",
                type: "Decimal",
                default: "Decimal(0.to_string())",
                skip: [1, 1, 1, 1, 1],
              },
              {
                name: "is_active",
                type: "i8",
                default: "1",
                skip: [1, 1, 1, 1, 1],
              },
            ],
        }
