project:
  template:
    dir: "templates/melon"
    output: "../../Java/hgtplat-inf"
  data:
    project_name: "hgtplat-inf"
    tasks: 
      - {
        name: "area"
      }
    tables:
      - {
          prefix: "e_third_",
          name: "area",
          cron: "0 0/1 * * * ?",
          columns:
            [
              {
                name: "id",
                type: "Long",
                dbType: "NUMBER(15)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "code",
                type: "String",
                dbType: "VARCHAR2(300)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "name",
                type: "String",
                dbType: "VARCHAR2(300)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "parentCode",
                type: "String",
                dbType: "VARCHAR2(300)",
                skip: [1, 1, 1, 1],
              },
            ],
          ddls: [],
        }
    ddls: [""]
