project:
  template:
    dir: "templates/guava"
    output: "../guava-erp"
  data:
    project_name: "guava-erp"
    auth: 1
    redis_session: 0
    pages:
      - {
          label: "系统管理",
          url: "/",
          children:
            [
              { label: "用户管理", tableName: "user" },
              { label: "租户管理", tableName: "tenant" },
              { label: "角色管理", tableName: "role" },
            ],
        }
    tables:
      # 租户
      - {
          prefix: "sys_",
          name: "tenant",
          skipAuto: true,
          columns:
            [
              {
                name: "id",
                type: "i64",
                dbType: "int8",
                skip: [1, 1, 1, 1],
              },
              {
                name: "name",
                type: "String",
                dbType: "varchar(120)",
                skip: [1, 1, 1, 1],
                ui: {
                  type: 'input-text',
                  label: '名称'
                },
              },
            ],
          ddls: ["create index idx_tenant_name on sys_tenant(name);"],
        }
      # 用户
      - {
          prefix: "sys_",
          name: "user",
          skipAuto: true,
          columns:
            [
              { name: "id", type: "i64", dbType: "int8", skip: [1, 1, 1, 1] },
              {
                name: "name",
                type: "String",
                dbType: "varchar(120)",
                skip: [1, 1, 1, 1],
                ui: {
                  type: 'input-text',
                  label: '名称',
                },
              },
              {
                name: "password",
                type: "String",
                dbType: "varchar(120)",
                skip: [1, 1, 1, 1],
                ui: {
                  type: 'input-password',
                  label: '密码'
                },
              },
              {
                name: "store_id",
                type: "i64",
                dbType: "int8",
                skip: [1, 1, 1, 1],
                ui: {
                  type: 'input-number',
                  label: '所属店铺'
                },
              },
              {
                name: "dept_id",
                type: "i64",
                dbType: "int8",
                skip: [1, 1, 1, 1],
                ui: {
                  type: 'input-number',
                  label: '所属部门'
                },
              },
            ],
          ddls: ["create index idx_user_name on sys_user(name);"],
        }
      # 角色
      - {
          prefix: "sys_",
          name: "role",
          columns:
            [
              { name: "id", type: "i64", dbType: "int8", skip: [1, 1, 1, 1] },
              {
                name: "name",
                type: "String",
                dbType: "varchar(120)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "description",
                type: "String",
                dbType: "varchar(120)",
                skip: [1, 1, 1, 1],
              },
            ],
          ddls: [],
        }
      # 菜单
      - {
          prefix: "sys_",
          name: "menu",
          columns:
            [
              { name: "id", type: "i64", dbType: "int8", skip: [1, 1, 1, 1] },
              { name: "pid", type: "i64", dbType: "int8", skip: [1, 1, 1, 1] },
              {
                name: "menu_name",
                type: "String",
                dbType: "varchar(120)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "path",
                type: "String",
                dbType: "varchar(120)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "component",
                type: "String",
                dbType: "varchar(120)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "perms",
                type: "String",
                dbType: "varchar(120)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "icon",
                type: "String",
                dbType: "varchar(120)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "ty",
                type: "String",
                dbType: "CHAR(2)",
                skip: [1, 1, 1, 1],
              },
              { name: "sort", type: "i64", dbType: "int8", skip: [1, 1, 1, 1] },
              {
                name: "description",
                type: "String",
                dbType: "varchar(120)",
                skip: [1, 1, 1, 1],
              },
            ],
          ddls: ["create index idx_menu_pid on sys_menu(pid);"],
        }
      # 用户角色关系
      - {
          prefix: "sys_",
          name: "user_role",
          columns:
            [
              { name: "id", type: "i64", dbType: "int8", skip: [1, 1, 1, 1] },
              {
                name: "user_id",
                type: "i64",
                dbType: "int8",
                skip: [1, 1, 1, 1],
              },
              {
                name: "role_id",
                type: "i64",
                dbType: "int8",
                skip: [1, 1, 1, 1],
              },
              {
                name: "description",
                type: "String",
                dbType: "varchar(120)",
                skip: [1, 1, 1, 1],
              },
            ],
          ddls:
            [
              "create index idx_user_role_user_id on sys_user_role(user_id);",
              "create index idx_user_role_role_id on sys_user_role(role_id);",
            ],
        }
      # 角色菜单关系
      - {
          prefix: "sys_",
          name: "role_menu",
          columns:
            [
              { name: "id", type: "i64", dbType: "int8", skip: [1, 1, 1, 1] },
              {
                name: "menu_id",
                type: "i64",
                dbType: "int8",
                skip: [1, 1, 1, 1],
              },
              {
                name: "role_id",
                type: "i64",
                dbType: "int8",
                skip: [1, 1, 1, 1],
              },
              {
                name: "description",
                type: "String",
                dbType: "varchar(120)",
                skip: [1, 1, 1, 1],
              },
            ],
          ddls:
            [
              "create index idx_role_menu_user_id on sys_role_menu(menu_id);",
              "create index idx_role_menu_role_id on sys_role_menu(role_id);",
            ],
        }

    ddls: []
