project:
  template:
    dir: "templates/guava"
    output: "../pt-test"
  data:
    project_name: "demandwall"
    table_ddls:
      - "create table demand(id int8, name text);"
    tables:
      - {
        name: "demand",
        columns: [
          {
            name: "id",
            type: "i64",
            skip: [1, 1, 1, 1]
          },
          {
            name: "name",
            type: "String",
            skip: [1, 1, 1, 1]
          },
        ]
      }
