project:
  template:
    dir: "templates/guava"
    output: "../pt-test"
  data:
    project_name: "pt-test"
    table_ddls:
      - "create table demand(id int8, name text, description text, dlike int8, status int4 );"
    tables:
      - {
          name: "demand",
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1] },
              { name: "description", type: "String", skip: [1, 1, 1, 1] },
              { name: "dlike", type: "i64", skip: [0, 1, 0, 0] },
              { name: "status", type: "i32", skip: [null, 0, 1, 1] },
            ],
        }
