project:
  template:
    dir: "templates/melon"
    output: "../../Java/weimob-data-inf"
  data:
    project_name: "weimob-data-inf"
    tasks: 
      - {
        name: "vip_info"
      }
    tables:
      - {
          prefix: "wm_",
          name: "vip_info",
          cron: "0 0/1 * * * ?",
          columns:
            [
              {
                name: "id",
                type: "Long",
                dbType: "NUMBER(10)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "wid",
                type: "String",
                dbType: "VARCHAR2(80)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "phone",
                type: "String",
                dbType: "VARCHAR2(80)",
                skip: [1, 1, 1, 1],
              },
            ],
          ddls: [],
        }
      - {
          prefix: "wm_",
          name: "vip_info_pages",
          columns:
            [
              {
                name: "id",
                type: "Long",
                dbType: "NUMBER(10)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "current_page",
                type: "Long",
                dbType: "NUMBER(10)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "total_page",
                type: "Long",
                dbType: "NUMBER(10)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "customer_start_time",
                type: "Long",
                dbType: "NUMBER(19)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "customer_end_time",
                type: "Long",
                dbType: "NUMBER(19)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "error_msg",
                type: "String",
                dbType: "VARCHAR2(500)",
                skip: [1, 1, 1, 1],
              },
            ],
          ddls: [],
        }
    ddls: [""]
