project:
  template:
    dir: "templates/guava"
    output: "../guava-erp"
  data:
    project_name: "guava-erp"
    tables:
      - {
          name: "category",
          ddls: [
           "create table category(id int8, name text, pid int8);"
          ],
          columns:
            [
              { name: "id", type: "i64", skip: [1, 1, 1, 1] },
              { name: "name", type: "String", skip: [1, 1, 1, 1] },
              { name: "pid", type: "i64", skip: [1, 1, 1, 1] },
            ],
        }
