project:
  template:
    dir: "templates/plum"
    output: "../../Java/plum"
  data:
    project_name: "plum"
    overview: true
    tables:
      - {
          prefix: "b_",
          name: "category",
          columns:
            [
              {
                name: "id",
                type: "Long",
                dbType: "INT8",
                skip: [1, 1, 1, 1],
              },
              {
                name: "pid",
                type: "Long",
                dbType: "INT8",
                # dbTypeWith: "constraint FK_category_pid references b_category(id)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "name",
                type: "String",
                dbType: "VARCHAR(120)",
                skip: [1, 1, 1, 1],
              },
            ],
          ddls: ["create index idx_category_pid on b_category(pid);"],
        }
      - {
          prefix: "sys_",
          name: "user",
          skipAuto: true,
          columns:
            [
              {
                name: "id",
                type: "Long",
                dbType: "INT8",
                skip: [1, 1, 1, 1],
              },
              {
                name: "name",
                type: "String",
                dbType: "VARCHAR(120)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "password",
                type: "String",
                dbType: "VARCHAR(120)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "store_id",
                type: "Long",
                dbType: "INT8",
                skip: [1, 1, 1, 1],
              },
              {
                name: "dept_id",
                type: "Long",
                dbType: "INT8",
                skip: [1, 1, 1, 1],
              },
            ],
          ddls: ["create index idx_user_name on sys_user(name);"],
        }
    ddls: [""]
