project:
  template:
    dir: "templates"
    output: "output"
    extension: "rs"
  data:
    project_name: "demandwall"
    table_ddls:
      - "create table book(id int8);"
    table_names:
      - "book"
      - "demand"
