project:
  template:
    dir: "templates/melon"
    output: "../../Java/melon"
  data:
    project_name: "melon"
    tables:
      - {
          prefix: "sys_",
          name: "tenant",
          skipAuto: true,
          columns:
            [
              {
                name: "id",
                javaType: "Long",
                dbType: "NUMBER(10)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "name",
                javaType: "String",
                dbType: "VARCHAR2(120)",
                skip: [1, 1, 1, 1],
              },
            ],
          ddls: ["create index idx_tenant_name on sys_tenant(name);"],
        }
      - {
          prefix: "sys_",
          name: "user",
          skipAuto: true,
          columns:
            [
              {
                name: "id",
                javaType: "Long",
                dbType: "NUMBER(10)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "name",
                javaType: "String",
                dbType: "VARCHAR2(120)",
                skip: [1, 1, 1, 1],
              },
            ],
          ddls: ["create index idx_user_name on sys_user(name);"],
        }
      - {
          prefix: "b_",
          name: "category",
          columns:
            [
              {
                name: "id",
                javaType: "Long",
                dbType: "NUMBER(10)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "pid",
                javaType: "Long",
                dbType: "NUMBER(10)",
                dbTypeWith: "constraint FK_category_pid references b_category(id)",
                skip: [1, 1, 1, 1],
              },
              {
                name: "name",
                javaType: "String",
                dbType: "VARCHAR2(120)",
                skip: [1, 1, 1, 1],
              },
            ],
          ddls: ["create index idx_category_pid on b_category(pid);"],
        }
    ddls: [""]
