# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created  
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path  
  
name: Maven Package  
  
on:  
  push:  
    branches:  
      - main  
  
jobs:  
  build:  
  
    runs-on: ubuntu-22.04  
    permissions:  
      contents: read  
      packages: write  
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up JDK 8  
        uses: actions/setup-java@v3  
        with:  
          java-version: '8'  
          distribution: 'temurin'  
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml  
          settings-path: $\{{ github.workspace }} # location for the settings.xml file  
  
      - name: Build with Maven  
        run: mvn -B package --file pom.xml  
  
      - name: rsync deployments  
        uses: burnett01/rsync-deployments@5.2  
        with:  
          switches: -avzr --delete  
          path: target/{{project_name}}-0.0.1-SNAPSHOT.jar deploy.sh  
          remote_path: /home/app  
          remote_host: $\{{ secrets.DEPLOY_HOST }}  
          remote_port: 22  
          remote_user: $\{{ secrets.DEPLOY_USER }}  
          remote_key: $\{{ secrets.DEPLOY_KEY }}  
      - name: restart server  
        uses: appleboy/ssh-action@v0.1.6  
        with:  
          host: $\{{ secrets.DEPLOY_HOST }}  
          username: $\{{ secrets.DEPLOY_USER }}  
          key: $\{{ secrets.DEPLOY_KEY }}  
          port: 22  
          script: |  
            chmod +x /home/app/deploy.sh  
            /home/app/./deploy.sh